---
title: "Mara's Analysis"
author: "Mara Alexeev"
date: "10/8/2020"
output: html_document
---
```{r libraries, warning=FALSE, message=FALSE}
#get relevant libraries
library(tidyverse)
library(forcats)
```


```{r}
#read in data and print
covidclass_without_labels <- read_csv("data_do_not_alter/covidclass_without_labels.csv")
covidclass_without_labels
```


```{r clean data}
#clean data to seperate strings and IDs and print
clean_data <- covidclass_without_labels %>%
  mutate(id_cc = `patientID|chief complaint|`) 

clean_data <- clean_data %>%
  separate(col = id_cc, into = c('id', 'cc1', 'cc2'), sep = "[|]", remove = F)

clean_data
```


```{r terms}
#create list of words likely for covid patient presentation
to_match <- c("short", "fever", "i l i", " ili ", "\\bili\\b","influe", "covid", "HYPOXIA", "DYSPNEA", "SOB")

pasted_match <- paste(to_match, collapse = "|")
```

```{r}
#use regex to search for covid likely terms
multi_search <- clean_data %>%
  mutate(covid_guess = as.integer(grepl(pattern = pasted_match, x = cc1, ignore.case = TRUE))) 


#multi_search$covid_guess <- ifelse(multi_search$cc1 %in% c("GAIT INSTABILITY"), multi_search$covid_guess == 0, multi_search$cc1)
```

```{r}
#count how many in the dataset resulted with covid likely terms
count_covid <- multi_search %>%
  group_by(covid_guess) %>%
  summarise(count = n())

count_covid
```
```{r}
#create covid only subset
subset_covid <- multi_search %>%
  filter(covid_guess == 1)
```

```{r}
#print out original dataset with covid prediction labels and save to csv:
group_predictions <- multi_search %>% select(id_cc, covid_guess)
write_csv(group_predictions, "./analysis/group_predictions.csv")

#print our guess for how many covid patients 
print(count_covid$count[2])

#print our output table
print(group_predictions)


```
```{r}

factored_covid <- subset_covid
factored_covid$cc1 <- as_factor(factored_covid$cc1)

group_by_cc1 <- factored_covid %>% 
  group_by(cc1) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

print(group_by_cc1)

```


